#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("finalTravelBlogger.Resource", IsApplication=true)]

namespace finalTravelBlogger
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brazil = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int canada = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int china = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int india = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int travel = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int travel1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int travelblog = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int usa = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060018
			public const int aboutBlogger = 2131099672;
			
			// aapt resource value: 0x7f060011
			public const int bloggerTextView = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int btnCall = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int btnEmail = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnMenu = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int btnSms = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int countryTextView = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int imageView1 = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int imgImage = 2131099668;
			
			// aapt resource value: 0x7f060007
			public const int imgMain = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int imgMain1 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int imgNextImage = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int item2 = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int listView = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int nextListView = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int photoImageView = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int tvCountry = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int tvIntroduction = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int tvNextBlogger = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int tvVisitedBlogger = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int tv_NextCountry = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int txtMessage = 2131099650;
			
			// aapt resource value: 0x7f060016
			public const int visitedLocation = 2131099670;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutBlogger = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NextDestination = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NextDestinationDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Splash = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TravelListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int VisitedLocation = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int VisitedLocationDetail = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
